### ISSUE TITLE
How will I add new language fonts?

### ISSUE THREAD

**Issue by Tomsan** [tantaman/Strut#102]
I work with a few Indian languages and I want to add fonts to the drop down. I have figured it out in the pre-Built package and done it by manually editing the code, is there a better way?

**Comment by morischu** [comment]
Hey, i would be interested in what you changed in the code to add new fonts to the drop-down. I'd like to do this at well for my own project.

Thanks!

**Comment by mwcz** [comment]
Because strut presentations are really just webpages, you can add custom fonts through the CSS panel.  That's what I do, at least.  It's not that usable for the normal end user, but most strut users seem to be programmery types.

**Comment by morischu** [comment]
Thanks! Yeah i tried this as well and added my fonts via @font-face to the css. But how do i embed the fonts so that they are visible in the dropdown menu in the editor?

**Comment by mwcz** [comment]
As far as I know that isn't possible, short of submitting a pull request that adds your font.  @tantaman might know better.

**Comment by tantaman** [comment]
yeah, I never got around to making fonts pluggable :/  

You may be able to just add them as new entries here:
https://github.com/tantaman/Strut/blob/master/app/bundles/app/strut.etch_extension/templates/fontFamilySelection.bars

and then add them to the final stylesheet.

**Comment by morischu** [comment]
Okay, thank you :D Where do i find this list in my prebuilt version of strut?

**Comment by mwcz** [comment]
@morischu you must edit the file that tantaman linked in order to add new fonts to the dropdown list.  You'll have to build strut after making that change.  Unfortunately you won't be able to make the change in a prebuilt strut.
