### ISSUE TITLE
"Try it free" graphic is off putting

### ISSUE THREAD

**Issue by oakbarrel** [tantaman/Strut#274]
Hi!

I used Strut a little bit in the past and decided to use it now for another project. When I went to the website strut.io, the first thing I saw was the "try it free" graphic and my instant reaction was "Oh crap, this software has become shareware/commercial and I have to look for an alternative". 

It's the case in 99% of websites that if a graphic says "try it for free" then you only get a free trial and then have to start paying.

If your intention is not to start charging money for strut, please clarify that on the website! "100% free open source" is like a big nice welcome mat. "Try it free" is like saying "grab your wallet and run away quickly" to many people.

I'm assuming Strut is still intending to stay a free right?

**Comment by seventurns** [comment]
Is this in the roadmap, a payware version?
