### ISSUE TITLE
building Strut :)

### ISSUE THREAD

**Issue by jen1979** [tantaman/Strut#295]
I need some pointers here, I found a version of Srut that does not upload your images to www.imgur unless you request that , it actually allows local storage which is great for privacy. I need to build this into a deployment version.

I looked for Grunt and npm to build the source code into a deployment. However, I cannot find a definitive version of Grunt or npm, it was like searching through a maze  of opinions. Can someone provide a direct single downlink.  Also for myself and others please can someone explain why I need to build the sourcecode into a deployment. Its in Javascript, i do not understand the necessity for building a deployment. There is no binary files , 

I had a stroke so i am not as sharp as i used to be, i am missing a few IQ points lol

Any help is appreciated

**Comment by 2braincells2go** [comment]
Pre-built version would be very nice. Like to deploy on a local network for school use. I am betting the kids would love to use Strut. No way for them to get online so must be ran on local network...

**Comment by kirbyfan64** [comment]
I think you could do something like [this](http://m.linuxjournal.com/content/downloading-entire-web-site-wget) to download the website.
