### ISSUE TITLE
Add audio

### ISSUE THREAD

**Issue by oxhey** [tantaman/Strut#310]
Is there an option where you can add a html5 audio player to each slide , similar to the video option?

**Comment by mwcz** [comment]
You can add any HTML you want if you use the Markdown option for slides.  You could try that with an <audio> tag.

You could even try using the Website tool and pasting the URL to your audio/video file into that.  If your web browser has a media-player plugin (most do these days), that may just work without any further effort.

**Comment by oxhey** [comment]
That kind of works . Its a bit zoomed out

**Comment by mwcz** [comment]
If you paste the file's URL into a new tab and zoom in there, then the embedded Website tool should also be zoomed inside your presentation.  That won't carry over if you switch browsers though.

The first approach I mentioned above is more flexible.  Use `<video>` or `<audio>` inside the Markdown text area.  You can use CSS to position it if you need to.  Or even something like [MediaElement.js](http://mediaelementjs.com/) if you want.  Up to you.
