### ISSUE TITLE
Failed to build due to "No compatible version found: phantomjs@'>=1.8.1 <1.9.0'"

### ISSUE THREAD

**Issue by lihuanshuai** [tantaman/Strut#316]
I try to build Strut on Linux Mint 17, but it failed. parts of the log:

```
17429 error Linux 3.13.0-24-generic
17430 error argv "node" "/usr/local/bin/npm" "--registry=https://registry.npm.taobao.org" "--cache=/home/lihs/.npm/.cache/cnpm" "--disturl=https://npm.taobao.org/dist" "--userconfig=/home/lihs/.cnpmrc" "install"
17431 error node v0.10.25
17432 error npm  v2.1.16
17433 error code ETARGET
17434 error notarget No compatible version found: phantomjs@'>=1.8.1 <1.9.0'
17434 error notarget Valid install targets:
17434 error notarget ["1.9.13","1.9.12","1.9.11","1.9.10","1.9.9","1.9.8","1.8.2-3","1.9.7-15","1.9.7-14","1.9.7-13","1.9.7-12","1.9.7-11","1.9.7-10","1.9.7-9","1.9.7-8","1.9.7-7","1.9.7-6","1.9.7-5","1.9.7-4","1.9.7-3","1.9.7-1","1.9.6-0","1.9.2-6","1.9.2-5","1.9.2-4","1.9.2-3","1.9.2-2","1.9.2-1","1.9.2-0","1.9.1-9","1.9.1-8","1.9.1-7","1.9.1-6","1.9.1-5","1.9.1-4","1.9.1-3","1.9.1-2","1.9.1-0","1.9.0-6","1.9.0-5","1.9.0-4","1.9.0-3","1.9.0-2","1.9.0-1","1.9.0-0","1.8.2-2","1.8.2-1","1.8.2-0","1.8.1-3","1.8.1-2","1.8.1-1","1.8.0-1","0.2.6","0.2.5","0.2.4","0.2.3","0.2.2","0.2.1","0.2.0","0.1.1","0.1.0","0.0.9","0.0.8","0.0.7","0.0.6","0.0.5","0.0.4","0.0.3","0.0.2","0.0.1"]
17434 error notarget
17434 error notarget This is most likely not a problem with npm itself.
17434 error notarget In most cases you or one of your dependencies are requesting
17434 error notarget a package version that doesn't exist.
```

It is obvious that there are serveral versions which match requirement, not npm fail to find one. it is so wierd

**Comment by tantaman** [comment]
I'm guessing this is during `npm install`?  Do you know which package is trying to include phantom? (Strut doesn't use phantom directly so some other package that Strut depends on is causing this problem)

**Comment by lihuanshuai** [comment]
yes, it is during `npm install`, and it is the dep chain: `grunt-mocha` <- `grunt-lib-phantomjs` <- `phantomjs`, i try installing the `phantomjs` version, but it always fail. the latest `phantomjs` version succeeds in  installation, but fails to match requirements

**Comment by cliffordsnow** [comment]
I received the same error message. But Strut seems to run just fine. So far I haven't seen any problems. (Although I haven't figured out where the new presentation file, .strut, is save.)

**Comment by Vallevard** [comment]
Hi, @lihuanshuai  not sure if you have already fixed this problem, but for me I just run:  `npm install grunt-mocha --save-dev `  then I run the command  `npm install`  and after that when I ran Strut `grunt server` the problem was fixed. Regards!

**Comment by lihuanshuai** [comment]
Hi, @Vallevard , my apologies for the very late reply. The problem is fixed, in exactly the way you said. Thanks!

**Comment by interfaceslivres** [comment]
thank you for this, it solved my issue too.

**Comment by nico202** [comment]
Same problem here. The way suggested by @lihuanshuai worked, but for new users like me, it's still something preventing me to install it (had to google a solution). This is a workaround more than a fix, maybe writing in the readme to help those struggling? :)
(However, thanks for the help, and for Strut that is really cool)

**Comment by okitoxd** [comment]
if the solution does not work @Vallevard, delete the line `"Grunt - mocha " : "~ 0.2.2"` of `package.json` and try

**Comment by samtux** [comment]
Thanks  @okitoxd!!!

**Comment by agustinramos** [comment]
Thanks @okitoxd!!!
