### ISSUE TITLE
Integrate Strut in my website

### ISSUE THREAD

**Issue by busilina** [tantaman/Strut#319]
Hi,

how could I integrate Strut in my website. Let's say I have a hyperlink and when someone clicks it, a new Tab or Window opens in the browser with Strut showing my file?

Thanks!

**Comment by mwcz** [comment]
1. View your presentation
 2. File / Save As (choose "Web page (complete)".  this will save an html file and all the CSS/JS/etc
 3. Copy all those files to your website
 4. add a link to the html file

**Comment by muhaNERD** [comment]
Well, I guess I simplified my question too much :) I actually wanted to know if there is any possibility to send a POST request to Strut with a file that I would like to edit. Any API for that?

**Comment by mwcz** [comment]
Ah!  Gotcha.  No, there's no API for that.  Strut is a pure front-end app,
so there's no server component besides the web server that delivers the
files.

It would be possible to modify Strut to open a WebSocket connection to a
server that does accept those POSTs, and the server could then deliver the
images over that connection.  What's your use case?

**Comment by muhaNERD** [comment]
I actually wanted to build a new Context-Menu entry (say: "Open with Strut"). So that I can right-click my document -> choose "open with Strut" -> the brwoser opens, loads Strut, import my document, and opens it.

**Comment by mwcz** [comment]
That can probably be done too.  If you launch Chrome with the `--allow-file-access-from-files` flag, it should enable you to have your context menu launch something like `google-chrome --allow-file-access-from-files $STRUT_URL?localFileImport=$CONTEXTFILE`.  That would give Strut browser permission to open that file.  It also gives Strut (or whatever web app you use this on) full access to your user's disk permissions, so be careful.  I trust Strut, but not that much.

Of course, you would have to add that feature to Strut for this to work.  But it is possible!

**Comment by tantaman** [comment]
@muhaNERD, that is an interesting idea. @mwcz is right in that Strut is purely client side but I've had a long standing goal to implement a backend for Strut although I haven't gotten around to it.  If / when there is an API I'll let you know.

**Comment by muhaNERD** [comment]
perfect! Well I am interested in contributing so let me know how I can help.
