### ISSUE TITLE
Integrate with my website

### ISSUE THREAD

**Issue by kb80** [tantaman/Strut#321]
How I can Integrate strut with my website?
I want to store the presentation and images on my webserver.
I want to open strut in iframe, and I want to have on my main site the button save to store the presentation edited in the iframe.

Regards

Konrad

**Comment by mwcz** [comment]
You could have the save button on your main page reach into the iframe's context and trigger the save function.

There currently isn't a way to store the presentation and images on your webserver, though.  Strut is a client-side-only app; there's no server component to handle authentication and reading/writing to the server's disk.

**Comment by tantaman** [comment]
You could implement a new storage provider that saved to a server...  if you want more details I can provide them.

**Comment by afrozl** [comment]
I would be interested in more details around a new storage provider. Particularly in the node.js/express world

**Comment by tantaman** [comment]
You can look at the existing storage bundle for "local storage" and
implement something similar for a web backend.
