### ISSUE TITLE
Exporting Question

### ISSUE THREAD

**Issue by bendparker** [tantaman/Strut#325]
Is there a way that on export, I could save the json file to the webserver Strut is running on as opposed to downloading?

**Comment by mwcz** [comment]
This isn't possible, currently.  Strut is a client-side-only app.  There's no server-side component to send the json to.  @tantaman has said that he's open to adding a server component in the future, though.  It would be nice to be able to save presentations on the server, plus it would allow for collaboration features to be built on top.

The best I can suggest for now is to save the json in a git repo, or owncloud/dropbox/google drive/etc. :/
