### ISSUE TITLE
Reveal Re-Intergration

### ISSUE THREAD

**Issue by oxhey** [tantaman/Strut#326]
I noticed that you have reveal integration previously , but removed it .

I use reveal and would like to get it working with Struct 0.6.3. I can see that in the preview_export folder there are some reveal.js related files. 

Is there any way to get it to work with reveal?

**Comment by tantaman** [comment]
You can make a new presentation generator.  You can look at the bespoke, impress and handouts generators as examples.

https://github.com/tantaman/Strut/tree/master/app/bundles/app/strut.presentation_generator.impress
https://github.com/tantaman/Strut/tree/master/app/bundles/app/strut.presentation_generator.bespoke
https://github.com/tantaman/Strut/tree/master/app/bundles/app/strut.presentation_generator.handouts

and apparently there is still some reveal code:
https://github.com/tantaman/Strut/tree/master/app/bundles/app/strut.presentation_generator.reveal

So there is a chance that the reveal bundle will work if you just add it to features.js: https://github.com/tantaman/Strut/blob/master/app/scripts/features.js
