### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by farfeduc** [tantaman/Strut#329]
Hi ! Small issue, if you use "grunt build" and then copy all the files in the dist folder to a webserver, the page is just gray (like in the official demo @ strut.io/editor on chrome).

For now I'm using the app folder on my webserver.

If it can be of any help.

Thanks for creating such a good app !

**Comment by tantaman** [comment]
wow... didn't realize something happened to the official demo.  Looks like
a bug in chrome since that site hasn't been updated in over a year and has
worked until now.  Refreshing the page resolves the issue for some reason.
Thanks for pointing this out.

**Comment by farfeduc** [comment]
Happy to help :)

**Comment by tantaman** [comment]
The problem is that Chrome now treats `function {}()` as a syntax error.  wrapping the built version with `(` makes it work.  E.g., change the outer most function from `function () {}()` to `(function (){})()`

strut.io/editor has been updated.  I'll push a code update to the build step.

**Comment by mwcz** [comment]
Weird, I really wonder how `function() {}()` worked before.  It should be a syntax error in all browsers.  A function statement can't be immediately invoked.  It has to be coaxed into a function expression (not statement) by wrapping it in parens or prefixing with an operator that turns the statement into an expression, like `!function() {}()` or `+function() {}()`.

I know I'm not helping here, just curious why it worked before and suddenly didn't. :)

**Comment by tantaman** [comment]
yeah... doesn't make sense to me either.  On the bright side it forced me
to figure out how my s3 buckets and iam users were configured again.
