### ISSUE TITLE
Add Bundle

### ISSUE THREAD

**Issue by HiagoAD** [tantaman/Strut#330]
Hi everyone, is not a issue is more a doubt, how can I add new bundles? I'm trying, but is always returning error 404 file don't find. Now, the only thing that I want is print "Worked!" on console but using bundle organization.

Please, help this young padawan :/

**Comment by tantaman** [comment]
Do you have an example of what you've tried so far?

**Comment by HiagoAD** [comment]
I tried to put on features.js the path to my .js file, dont worked. Then I add 'strut/anim' : '../bundle/app/strut.anim' and when I debbuged came the 404, but the path was right.

**Comment by tantaman** [comment]
Can you put a diff up?  Assuming you've forked strut you can commit your
changes and push them to your fork and I can take a look.
