### ISSUE TITLE
tools not worrking in chrome

### ISSUE THREAD

**Issue by bluenevus** [tantaman/Strut#331]
going to strut.io and installing it both results in the text, images or anything added to the presentation unable to move, resize or edit the object.  Seems to work just fine in firefox though.  Just not in chrome.

**Comment by tantaman** [comment]
What os and version of chrome? Can't reproduce on my Mac.

**Comment by bluenevus** [comment]
Chrome version Version 42

Windows 8.1, Windows 7, Linux Mint 17, chrome os

Doesn't work on any of the machines in chrome.  Works in firefox though.

**Comment by tantaman** [comment]
If you open the console do you see any errors?

**Comment by bluenevus** [comment]
Turns out its a plugin of sorts.  I disabled all chrome extension and it worked fine.  I'll go through each extension to figure out which one caused the issue

**Comment by nilskp** [comment]
Even without plugins, this is not working in Chrome. I'm using 44.0.2403.155 m (64-bit).

It starts up with text, but the text can't be closed, nor resized, or anything else. It's as if the grabbing of controls doesn't register. There are no errors in console.

**Comment by mwcz** [comment]
Just tested on chrome Version 44.0.2403.155 m in Windows 7 32-bit and I was able to add text, resize it, move it, add shapes, etc.  Odd.

**Comment by Vallevard** [comment]
I tested on  chrome Version 44.0.2403.155 m in Windows 7 64-bit and I was unable to move, resize or edit the objects, but if I try to move, resize or edit using the touchscreen feature it works.

**Comment by nilskp** [comment]
Ahh, that might explain something. I'm using a laptop with touchscreen, although with an external monitor, so I can't actually use that as a workaround. But knowing the likely cause might help in debugging this.

I should add that my Chrome dropdown has the "Relaunch Chrome in Windows 8 mode" option, meaning it's _not_ in that mode.

**Comment by truburt** [comment]
Same thing here, laptop with touchscreen, Chrome 47, can't move or change anything with a mouse. Touchscreen is working fine.
