### ISSUE TITLE
Want to have a simple Pop up

### ISSUE THREAD

**Issue by SubstanceD** [tantaman/Strut#333]
How can i have a simple pop up in slides

When i hover mouse a popup box should come?

http://jsfiddle.net/9RxLM/

Something like this but it does not seem to work...

**Comment by mwcz** [comment]
If you share your slide deck we can probably help figure out why it isn't working.

My first guess would be that you need to includ, in the markdown code for the first slide, a `<script>` tag that includes jQuery.

**Comment by SubstanceD** [comment]
Thanks.. I got it. Using a pretty simple css based trick.

https://jsfiddle.net/substance_d/9RxLM/4457/

**Comment by mwcz** [comment]
Nice!
