### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by portnoy** [tantaman/Strut#334]
npm ERR! Darwin 12.6.0
npm ERR! argv "node" "/Users/eugene/.node/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.13.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: phantomjs@'>=1.8.1 <1.9.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9","0.1.0","0.1.1","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","1.8.0-1","1.8.1-1","1.8.1-2","1.8.1-3","1.8.2-0","1.8.2-1","1.8.2-2","1.9.0-0","1.9.0-1","1.9.0-2","1.9.0-3","1.9.0-4","1.9.0-5","1.9.0-6","1.9.1-0","1.9.1-2","1.9.1-3","1.9.1-4","1.9.1-5","1.9.1-6","1.9.1-7","1.9.1-8","1.9.1-9","1.9.2-0","1.9.2-1","1.9.2-2","1.9.2-3","1.9.2-4","1.9.2-5","1.9.2-6","1.9.6-0","1.9.7-1","1.9.7-3","1.9.7-4","1.9.7-5","1.9.7-6","1.9.7-7","1.9.7-8","1.9.7-9","1.9.7-10","1.9.7-11","1.9.7-12","1.9.7-13","1.9.7-14","1.9.7-15","1.8.2-3","1.9.8","1.9.9","1.9.10","1.9.11","1.9.12","1.9.13","1.9.15","1.9.16","1.9.17"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'grunt-lib-phantomjs'
npm ERR! notarget

the version I have installed is:
  description: 'Headless WebKit with JS API',
  'dist-tags': { latest: '1.9.17', alpha: '2.0.0-alpha' },

**Comment by SalimF** [comment]
I just got similar is issue and i solve it adding this command before npm install
```
       npm install grunt-mocha --save-dev 
       'npm install

**Comment by namesmile** [comment]
@portnoy update package.json dependency
```"grunt-mocha": "~0.4.15"```

**Comment by portnoy** [comment]
@sunthera Thank you!
