### ISSUE TITLE
Customize strut.io for our company Deutsche Bahn

### ISSUE THREAD

**Issue by morischu** [tantaman/Strut#335]
Hey there,

i'm Moritz Schuchmann from the german company Deutsche Bahn. We want to build a business service for dynamic presentations and we're using strut as basic framework. First of all: Thumbs up for what you created till here!

Now, that we can make the prototype more custom for our service, i have a couple of questions (i hope they haven't been asked already, didn't find them):
1. Is there a simple way to add custom fonts and colors (of our corporate design) to the strut-editor?
2. Can we add our graphics (best would be svg-files) to the shapes in the editor? How would you do that?
3. Does strut.io has a function to create custom templates that our users can start building their presentations on?

Thank you very much

Moritz Schuchmann (DB Systel GmbH)
moritz.schuchmann@deutschebahn.com

**Comment by tuonglx** [comment]
for #2 [https://github.com/tantaman/Strut/issues/318]
