### ISSUE TITLE
Near zero functionality

### ISSUE THREAD

**Issue by francoisgervais** [tantaman/Strut#336]
Hello,

Long time user of Strut, apparently I broke something fierce. 
- I am able to add, re-order and remove slides.
- I am able to add elements (text, images, shapes, etc) from the top menu.
- I am able to change background and surface colours to the default choices, not able to specify new ones.
- Once an element is on the canvas, aside from moving it around via changing the x y value boxes or changing colours from the default choices offered, I have zero interaction with anything. I can't edit content, basically.
- In the overview tab I am able to play with content in the text boxes and change the x y orientation, any change to the z axis will take effect but when previewing the presentation the camera will not pivot to stay in front of the new slide.

Console:
LOADING LODASH!!!!
amd-app.js:11 Loaded mirror
amd-app.js:6 The specified value '!' does not conform to the required format.  The format is '#rrggbb' where rr, gg, bb are two-digit hexadecimal numbers.
amd-app.js:29 Initing
amd-app.js:25 New file name: presentation-5
strut-icon.png:1 GET http://strut.io/editor/img/strut-icon.png 404 (Not Found)
strut-icon.png:1 GET http://strut.io/editor/img/strut-icon.png 404 (Not Found)
strut-icon.png:1 GET http://strut.io/editor/img/strut-icon.png 404 (Not Found)
amd-app.js:22 DISPOSING CONTEXT MENU!

Version 44.0.2403.125 m of Chrome

**Comment by tantaman** [comment]
Are you using strut.io or your own build?
