### ISSUE TITLE
Problem building strut

### ISSUE THREAD

**Issue by morischu** [tantaman/Strut#337]
Hey,

i opened cmd on my windows computer and typed in: npm install -g grunt-cli

Then i got the following error-message:
![unbenannt](https://cloud.githubusercontent.com/assets/13417312/9082136/37eef942-3b62-11e5-8daf-660285dc3d19.PNG)

What am i doing wrong? Where do i have to store my strut-master?

Thanks!

**Comment by mwcz** [comment]
Were you connected to the internet at the time?  This is a network connectivity problem, not an issue with strut or npm.

**Comment by morischu** [comment]
yes i was.. But i'm in our company-network, maybe there is a proxy making problems?

**Comment by tantaman** [comment]
There should be some guides online to getting npm to go through your
corporate proxy:
http://wil.boayue.com/blog/2013/06/14/using-npm-behind-a-proxy/

**Comment by morischu** [comment]
Hey tantaman, thanks for your answer, but, it still doesn't work for me.. Could you pre-build the strut for our company Deutsche Bahn ( www.deutschebahn.com ) and then share it with me? That would be really nice! As i said, our company is very interested in your product and may be interested in a longer cooperation. That could be a good thing for you too.;)
You can Mail me here: moritz.schuchmann@deutschebahn.com

**Comment by 2braincells2go** [comment]
Following this also as cannot get through school firewall. Locked down tighter than my mums medicine cabinet:)

**Comment by tantaman** [comment]
And http://strut.io isn't an option for you? :o
