### ISSUE TITLE
strut.io out-dated ?!?

### ISSUE THREAD

**Issue by jedie** [tantaman/Strut#340]
On strut.io is the gh-pages branch, isn't it?

I just compare:
- https://github.com/tantaman/Strut/commits/gh-pages (Last commit Oct 24, 2013)
- https://github.com/tantaman/Strut/commits/master (Last commit May 3, 2015)

So, strut.io is not up-to-date ?!?

**Comment by mwcz** [comment]
Correct.

**Comment by mwcz** [comment]
See [this comment](https://github.com/tantaman/Strut/issues/285#issuecomment-67411306) by the author for the reason why.

**Comment by tantaman** [comment]
Strut.io is not run off of github pages so not totally correct.  Strut.io
should roughly match master

**Comment by patilshilpa** [comment]
hi i executed your code in my machine  but i need to use in my project can anybody suggest me how to use it .i trying it  but i am unable to understand your file format.....
