### ISSUE TITLE
Resizing of image, text etc are constrained

### ISSUE THREAD

**Issue by ironmaniiith** [tantaman/Strut#346]
Hi.
I am unable to resize the image or text on strut in an unconstrained manner. I want to integrate in a website in such a way that I can resize an image in any dimension (without actually caring about the aspect ratio).
Thanks.

**Comment by mwcz** [comment]
Hold shift while resizing. :D

**Comment by ironmaniiith** [comment]
Thanks. :+1:

**Comment by mwcz** [comment]
Hopefully this works, I recorded how it works for me with images: https://zippyy.com/share/strut-resize-aspect.webm

I just tried with text and it didn't work, though.  That feature could certainly be added (via CSS `transform: scaleX` and `transform: scaleY`), but it doesn't appear to exist right now.

**Comment by ironmaniiith** [comment]
Ya, thanx, it's working fine for images but not for the text.

**Comment by mwcz** [comment]
I'm not actually very familiar with Strut's codebase.  I'm just a user, so I'm not sure where to look.  But I do know you can adjust the "height" and "width" of text using the CSS transform `scale`.  Here's an example to work from:

http://jsfiddle.net/mxr7c0hs/

**Comment by ironmaniiith** [comment]
Ok, I'll try to figure it myself, Thanks. :+1:
