### ISSUE TITLE
maybe a nice feature: some basic text animation

### ISSUE THREAD

**Issue by cocodrino** [tantaman/Strut#350]
Hi, I know than prezi doesnt have this feature but I think than would be nice some basic animation tools, for instance, increase font or move inside the same frame,fade,transparencies,etc , I think than it's pretty possible right now using ccs but for me it's not pretty clear how achieve this...and would be really cool if strut has a tool for it...

this is a related impress discussion: 
https://github.com/impress/impress.js/issues/81

thanks!

**Comment by tuonglx** [comment]
Please do it

**Comment by tuonglx** [comment]
Is there any one working on this?

**Comment by mwcz** [comment]
To the best of my knowledge, Strut is not being actively developed.
