### ISSUE TITLE
Unable to edit after json export/import

### ISSUE THREAD

**Issue by peemblis** [tantaman/Strut#352]
Hi, 

I exported my presentation to json. On a different computer, I imported it. I am able to view it and change the background. However, I cannot edit the text, change the text colors, etc. Most of the functionality doesn't seem available. I'm using Chrome on Windows.

Thanks! 

Peng

**Comment by mwcz** [comment]
When this happens, are there any errors in the JavaScript console?  You can check by pressing F12 and clicking the Console tab.

**Comment by peemblis** [comment]
Hi mcwz,

Here's the console message:

LOADING LODASH!!!!
amd-app.js:11 Loaded mirror
amd-app.js:6 The specified value "!" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.
amd-app.js:29 Initing
amd-app.js:17 
amd-app.js:25 New file name: subro_analytics_day_v3.strut

**Comment by peemblis** [comment]
It appears to be an issue with Chrome. I can continue developing the presentation in Cyberfox (thank goodness!).

**Comment by mwcz** [comment]
It looks like this bug is caused by the Spectrum color picker ([issue here](https://github.com/bgrins/spectrum/issues/291)).

@peemblis can you try visiting my Strut instance, where I've updated Spectrum, and let me know if you still see the error? http://strut-mwcz.rhcloud.com/

**Comment by peemblis** [comment]
Hi mwcz, 

It appears to work as usual on that instance!  

Peng

**Comment by peemblis** [comment]
Is that instance open for use?

Peng

**Comment by peemblis** [comment]
Btw, is there a way to get rid of the "Use spacebar or arrow keys to navigate" that shows up during impress mode on the first step/slide?

**Comment by mwcz** [comment]
Sure, you're free to use that instance.  I set it up because I wanted a Strut that embedded images in the presentation instead of uploading them to Imgur.  I can't guarantee it'll always be up but it's been up for about a year with no issues. :)

As for the Impress message, add this to your presentation's CSS: `.hint { display: none; }`

**Comment by peemblis** [comment]
Thank you very much. This is an awesome tool!

**Comment by mwcz** [comment]
Happy to help!

**Comment by peemblis** [comment]
Hi tantaman,

Is there an easy way for "within" slide animation using impress/strut?
E.g., if I want to withhold a particular piece of information on a
particular slide and bring it in with a mouse click or arrow button (i.e.,
power point like).

Peng
