### ISSUE TITLE
Use and save local images

### ISSUE THREAD

**Issue by Defossez** [tantaman/Strut#359]
Hi,

Installed Strut locally.
When wanting to insert a local, stored in a folder, figure (.svg, .png or .jpg) the "insert image" pop up box has the text "Local images are currently uploaded to imgur. We're working on changing this".
How can I insert local graphics and leave them locally stored (I don't want that my images are uploaded somewhere else than on my PC).
By the way, browsing and selecting a local stored image and then hit [open] reslts in the error "Failed to upload image to imgur"

Thanks,

Marc

**Comment by mwcz** [comment]
There was a patch by @zamentur a while back that added embedding of images as base64-encoded strings.  I'm using it on my strut deployment at http://strut-mwcz.rhcloud.com/ since I also don't want to use imgur.  Ah, it was PR https://github.com/tantaman/Strut/pull/313.  Feel free to use my instance if you like (it's client only and *nothing* is stored on the server) or apply that patch to your local isntance.

**Comment by Defossez** [comment]
Thanks!
    I'll try it out
    
    Marc
    
      
      
      
      
      
      
      
      
      
        
      
      
        P
        Please do not
              print this
              e-mail unless you really need to.
      This email and
            any
            attachments are intended for the sole use of the named
            recipient(s)
            and contain(s) confidential information that may be
            proprietary,
            privileged or copyrighted under applicable law. If you are
            not the
            intended recipient, do not read, copy, or forward this email
            message
            or any attachments. Delete this email message and any
            attachments
            immediately. 
      
    
    On 04-02-16 15:51, mwcz wrote:
    
    
      There was a patch by @zamentur
        a while back that added embedding of images as base64-encoded
        strings. I'm using it on my strut deployment at http://strut-mwcz.rhcloud.com/
        since I also don't want to use imgur. Ah, it was PR #313.
        Feel free to use my instance if you like (it's client only and nothing
        is stored on the server) or apply that patch to your local
        isntance.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Defossez** [comment]
Hi,
    
    Thanks again.
    Applied you fix to my setup and it works perfect.
    
    Kind regards,
    
    Marc
    
      
      
      
      
      
      
      
      
      
        
      
      
        P
        Please do not
              print this
              e-mail unless you really need to.
      This email and
            any
            attachments are intended for the sole use of the named
            recipient(s)
            and contain(s) confidential information that may be
            proprietary,
            privileged or copyrighted under applicable law. If you are
            not the
            intended recipient, do not read, copy, or forward this email
            message
            or any attachments. Delete this email message and any
            attachments
            immediately. 
      
    
    On 04-02-16 15:51, mwcz wrote:
    
    
      There was a patch by @zamentur
        a while back that added embedding of images as base64-encoded
        strings. I'm using it on my strut deployment at http://strut-mwcz.rhcloud.com/
        since I also don't want to use imgur. Ah, it was PR #313.
        Feel free to use my instance if you like (it's client only and nothing
        is stored on the server) or apply that patch to your local
        isntance.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by mwcz** [comment]
Happy to help!  Can you close this issue?

**Comment by Defossez** [comment]
Done
    
      
      
      
      
      
      
      
      
      
        
      
      
        
        
        
        Marc
          Defossez
        Volmolenheide
          38
          2400 Mol – Antwerpen    Tel: +32 14 319
          632
          Belgium           
                        
          Eml: marc.defossez@gmail.com
      
        P
        Please do not
              print this
              e-mail unless you really need to.
      This email and
            any
            attachments are intended for the sole use of the named
            recipient(s)
            and contain(s) confidential information that may be
            proprietary,
            privileged or copyrighted under applicable law. If you are
            not the
            intended recipient, do not read, copy, or forward this email
            message
            or any attachments. Delete this email message and any
            attachments
            immediately. 
      
    
    On 05-02-16 13:02, mwcz wrote:
    
    
      Happy to help! Can you close this issue?
      —
        Reply to this email directly or view
          it on GitHub.
