### ISSUE TITLE
Error while building - no compatible version found for phantomjs

### ISSUE THREAD

**Issue by lapineige** [tantaman/Strut#363]
Hello,

> To build your own version of Strut you'll need Grunt v0.4.0 or later.

```
Install the latest Grunt: npm install -g grunt-cli
Clone Strut: git clone git://github.com/tantaman/Strut.git
cd Strut
Install Strut's development dependencies: npm install
Run Strut: grunt server (the server runs at localhost:9000)
```

I'm block at the step: `npm install`

I have this error message:

```
npm ERR! No compatible version found: phantomjs@~1.8.1
npm ERR! Valid install targets:
npm ERR! 2.1.7, 2.1.3, 2.1.3-deprecated, 2.1.2, 2.1.1, 1.9.20, 1.9.19, 1.9.18, 1.9.17, 1.9.16, 1.9.15, 1.9.13, 1.9.12, 1.9.11, 1.9.10, 1.9.9, 1.9.8, 1.9.7-15, 1.9.7-14, 1.9.7-13, 1.9.7-12, 1.9.7-11, 1.9.7-10, 1.9.7-9, 1.9.7-8, 1.9.7-7, 1.9.7-6, 1.9.7-5, 1.9.7-4, 1.9.7-3, 1.9.7-1, 1.9.6-0, 1.9.2-6, 1.9.2-5, 1.9.2-4, 1.9.2-3, 1.9.2-2, 1.9.2-1, 1.9.2-0, 1.9.1-9, 1.9.1-8, 1.9.1-7, 1.9.1-6, 1.9.1-5, 1.9.1-4, 1.9.1-3, 1.9.1-2, 1.9.1-0, 1.9.0-6, 1.9.0-5, 1.9.0-4, 1.9.0-3, 1.9.0-2, 1.9.0-1, 1.9.0-0, 1.8.2-3, 1.8.2-2, 1.8.2-1, 1.8.2-0, 1.8.1-3, 1.8.1-2, 1.8.1-1, 1.8.0-1, 0.2.6, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.1, 0.1.0, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
```

So I have no valid target to install, and v1.8.1 is not available. Is it a problem from strut dependency requirements, or a npm bug ?

Thanks for your help :)

**Comment by dikdust** [comment]
+1  tried on Ubuntu 16.04 64 bit

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! No compatible version found: phantomjs@~1.8.1
npm ERR! Valid install targets:
npm ERR! 2.1.7, 2.1.3, 2.1.3-deprecated, 2.1.2, 2.1.1, 1.9.20, 1.9.19, 1.9.18, 1.9.17, 1.9.16, 1.9.15, 1.9.13, 1.9.12, 1.9.11, 1.9.10, 1.9.9, 1.9.8, 1.9.7-15, 1.9.7-14, 1.9.7-13, 1.9.7-12, 1.9.7-11, 1.9.7-10, 1.9.7-9, 1.9.7-8, 1.9.7-7, 1.9.7-6, 1.9.7-5, 1.9.7-4, 1.9.7-3, 1.9.7-1, 1.9.6-0, 1.9.2-6, 1.9.2-5, 1.9.2-4, 1.9.2-3, 1.9.2-2, 1.9.2-1, 1.9.2-0, 1.9.1-9, 1.9.1-8, 1.9.1-7, 1.9.1-6, 1.9.1-5, 1.9.1-4, 1.9.1-3, 1.9.1-2, 1.9.1-0, 1.9.0-6, 1.9.0-5, 1.9.0-4, 1.9.0-3, 1.9.0-2, 1.9.0-1, 1.9.0-0, 1.8.2-3, 1.8.2-2, 1.8.2-1, 1.8.2-0, 1.8.1-3, 1.8.1-2, 1.8.1-1, 1.8.0-1, 0.2.6, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.1, 0.1.0, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

[npm-debug-log.txt](https://github.com/tantaman/Strut/files/752548/npm-debug-log.txt)

**Comment by daconcei472** [comment]
If anyone cares, this is caused by the mocha dep. Update to     "grunt-mocha": "0.4.14" and install works.

**Comment by lapineige** [comment]
Well, I do care, thanks @daconcei472 ! :)
