### ISSUE TITLE
Strut server

### ISSUE THREAD

**Issue by lucianopes** [tantaman/Strut#364]
Hi Tantaman,
is strut still active ? I love this project and i am looking the way to improve it  in the server side for an educational project, but i am encountering some difficulties. To save the contents of a presentation in the server side i must have the json file contents . I can get the html content of the presentation but not the json file, that you can have only via downloading. Any advise about to get the json file of the presentation content  ? Somethime like a function 'Save presentation' that  you can have the json text of the presentation. I have studied the 'amd-app.js' file, where i suppose there is the solution, but it seems to me very  intricate and complicated to understang the code. 
Thanks in advance.

**Comment by mwcz** [comment]
Strut is not active, but you should be able to find what you need anyway.  There is already a menu item called "Export" that does exactly what you described.  [This](https://github.com/tantaman/Strut/tree/master/app/bundles/app/strut.exporter.json) looks like it's the code you're looking for, although I won't be much help deciphering it.  Good luck!

**Comment by lucianopes** [comment]
Thanks, what a pity, it was a very nice project.

**Comment by abmxer** [comment]
@lucianopes Have you found out a solution to save content server side? Thanks
