### ISSUE TITLE
Strut for PHP

### ISSUE THREAD

**Issue by geokongo** [tantaman/Strut#365]
Hey guys... 

I figured out strut is a beautiful inactive project. I needed this feature though for an e-learning platform, so I fleshed out the necessary libraries and created a CodeIgniter app with exact same user interface here https://github.com/geoffreybans/presentation-codeigniter . 

Let me know your thoughts...

**Comment by jsriot** [comment]
Good work but Strut 2 has a lot of bug fixes...try making that rather than working with the one with a lot of bugs
https://github.com/tantaman/Strut2

**Comment by tantaman** [comment]
strut2 has barely any features yet ;)  so doing this for strut1 seems fine to me.
