### ISSUE TITLE
Problem to get Strut to run

### ISSUE THREAD

**Issue by waxweazle2001** [tantaman/Strut#367]
We want to user Strut in our Infrastructure. We installed an XAMPP and copied the complete folder on the htdocs folder. Now we changed the Apache Port to Port 81 and want to open the application with "localhost:81/Strut/app/index.html" but all we get is an grey site. Did we do something wrong or do we need to configure something before we can run the application?
I Missed a Manual how to Install the Application for People who are not so involved in making websites. ;-)

Greetings 
Wax

**Comment by 2braincells2go** [comment]
For initial setup, make sure you have followed the instructions: https://github.com/tantaman/Strut#developmentbuilding

This may help you if having issues setting up:

https://github.com/tantaman/Strut/issues/365

**Comment by geoffreybans** [comment]
You will need to generate the compressed template files first using Nodejs before it can run. I can help you set it up on Skype here exp.geoff

**Comment by waxweazle2001** [comment]
Hello from here,

I try looked thru the Instructions for the application, it seems like I'm programming the hole application myself. This is to complex to run it on 3 Workstations in our company. So I think I need to buy a Programm which got the same functions with an install routine. We need it standalone so I need to do this on all 3 workstations. That's to much work for it.
But THX for the offer to help via Skype.

**Comment by tantaman** [comment]
http://strut.io is back up and running.
