### ISSUE TITLE
Moving from Bootsrap to Semantic

### ISSUE THREAD

**Issue by ramezrafla** [tantaman/Strut#371]
@tantaman 
This project is superb! Well done!

Our own webapp uses Semantic-UI (which is really solid, and growing exponentially -- we moved to it from Bootstrap a year ago). How much of bootstrap are you really using? In other words, is it mostly the menu and modals or also during editing of the slides. If it's not too major of a task, we could work on a Semantic-UI version.

**Comment by tantaman** [comment]
you want to take a stab at it? :)

I doubt the juice is really worth the squeeze though.  There isn't too much styling going on in the project.

**Comment by ramezrafla** [comment]
Thanks @tantaman, the problem is that there are some documented collisions with bootstrap. Also, to have same look and feel as rest of our app and reduce download footprint (through UI reuse). 

Good to hear that styling is minimal, which makes sense.
