### ISSUE TITLE
Still active maintained project?

### ISSUE THREAD

**Issue by petrk94** [tantaman/Strut#372]
Hello,
I would like to know whether the repository is still active in development or not?

**Comment by tantaman** [comment]
It wasn't, but it is now.

**Comment by petrk94** [comment]
Great!

**Comment by tantaman** [comment]
@petrk94 - I'll be making strut2 "markdown first" when it comes to editing individual slides. The idea is to focus more on rapid authoring of presentations.

**Comment by tantaman** [comment]
I put some details around the vision into the readme: https://github.com/tantaman/strut2/blob/master/README.md

**Comment by petrk94** [comment]
@tantaman  https://github.com/tantaman/strut2 is dead , cant be found :(

**Comment by tantaman** [comment]
See the latest version of the Strut readme https://github.com/tantaman/Strut/blob/master/README.md
