### ISSUE TITLE
Fatal error: Unable to find local grunt.

### ISSUE THREAD

**Issue by zerkc** [tantaman/Strut#373]
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started

**Comment by theWebalyst** [comment]
The above helped, but didn't work for me. Instead I did NOT edit Gruntfile.js, and did the following:
```
	npm install grunt --save-dev
	npm install grunt-contrib-jshint --save-dev
	npm install connect-livereload  --save-dev
	npm install grunt-contrib-watch --save-dev
	npm install matchdep --save-dev
	npm install grunt-contrib-clean --save-dev
	npm install grunt-contrib-concat --save-dev
	npm install grunt-contrib-connect --save-dev
	npm install grunt-contrib-copy --save-dev
	npm install grunt-contrib-cssmin --save-dev
	npm install grunt-contrib-handlebars --save-dev
	npm install grunt-contrib-htmlmin --save-dev
	npm install grunt-contrib-imagemin --save-dev
	npm install grunt-contrib-livereload --save-dev
	npm install grunt-contrib-requirejs --save-dev
	npm install grunt-contrib-uglify --save-dev
	npm install grunt-open --save-dev
	npm install grunt-text-replace --save-dev
	npm install grunt-usemin --save-dev
	npm install

	grunt server
```

Now I seem to have a functioning Strut at localhost:9000

**Comment by dmwysocki61** [comment]
This doesn't work. Is there a more current resolution anywhere?

**Comment by tantaman** [comment]
I was able to get a fresh clone of strut running today.

Steps:

```
npm install
npm server
```
