### ISSUE TITLE
I have a problem to build Strup app!

### ISSUE THREAD

**Issue by dmitrirussu** [tantaman/Strut#376]
Hi I have a problem to build app. I get after build on run /dist next error: looks like the scripts are isolated does not have access to this element! why that became a problem?

TypeError: this is undefined
http://strut.local/dist/scripts/amd-app.js
Line 2

"...tes",["handlebars"],function(a){return this.JST=this.JST||{},this.JST["strut.etc..."

**Comment by dmitrirussu** [comment]
Also I had a problem for Mismatched anonymous define() modules ..., there is a lot of anonim define

**Comment by tantaman** [comment]
Strut should be building again. Someone contributed some changes in the last 3 years that fixed this.
