### ISSUE TITLE
¿Hoy can I overlap a image or a text?

### ISSUE THREAD

**Issue by mayrascript** [tantaman/Strut#377]
I wan to overlap a text or a image but I can't.

On dashboard:

![screen shot 2017-06-28 at 12 45 45 pm](https://user-images.githubusercontent.com/15218336/27652044-e886aaba-5bff-11e7-983a-4c6db21282b5.png)

Preview

![screen shot 2017-06-28 at 12 45 54 pm](https://user-images.githubusercontent.com/15218336/27652051-ede98b62-5bff-11e7-96ec-9410ff80cf4e.png)

**Comment by vadi2** [comment]
You might have to use an image editor, put one on top of another and use that as 1 big picture. Would that work?
