### ISSUE TITLE
How can I load the strut editor in pop-up?

### ISSUE THREAD

**Issue by dhara-pyrumas** [tantaman/Strut#378]
How can I load "container-fluid" div inside another div? I want to display the editor in pop-up, but it's loading at the bottom of the page.

   I've also created issue on [stackoverflow](https://stackoverflow.com/questions/45437977/how-can-i-load-the-strut-editor-in-pop-up). Please help, I'm trying to resolve this from last three days

**Comment by dhara-pyrumas** [comment]
Anyone?

**Comment by kirbyfan64** [comment]
Using HTML elements in areas that they're not designed for is a finicky beast at best and a nightmare at worst. Have you tried loading Strut in an iframe?
