### ISSUE TITLE
Strut.io not working for me

### ISSUE THREAD

**Issue by kadkarol** [tantaman/Strut#382]
After running strut.io, I see a gray page.
System: ubuntu 16.04, firefox 60
Widnows 8, firefox 59

Console
`SyntaxError: missing ) in parenthetical require.js:1:712`

**Comment by fenglu09** [comment]
Me too

**Comment by stoufa** [comment]
Same here !
I even sent an email to support@strut.io and I received a Address not found error from Gmail's Mail Delivery Subsystem ! what went wrong ?!

**Comment by vikumDheemantha** [comment]
I also have the same problem. When I try in strut.io/editor it only display me a Gray screen. When I clone and try to run it it also give an error. Seems like this repo is abandoned by its developers.

**Comment by Erudition** [comment]
Yup. Strut is broken

**Comment by tantaman** [comment]
This has been resolved as of today.

http://strut.io/editor
