### ISSUE TITLE
come and find out

### ISSUE THREAD

**Issue by leo-kogler** [tantaman/Strut#384]
Dear Matt, in my opinion your design or furthermore your code got stolen to an commercial product.

Please study these pages: https://prezi.com/

I only wanted to highlight this, because i also think that they're blocking or disabling strut.io for some users.

Yours

leo-kogler

**Comment by kirbyfan64** [comment]
Prezi came before Impress.js, which in turn is what Strut uses. Therefore, technically, Impress.js got its ideas from Prezi.

**Comment by leo-kogler** [comment]
what you re telling is completly nonsense.
prezi is closed source, how could someone copy closed source?

pls think twice before you write

**Comment by kirbyfan64** [comment]
The fact is simply that *Impress.js was inspired by Prezi*, not the other way around. Being closed source has nothing to do with it; you don't have to be able to access the code in order to be able to use similar ideas.

**Comment by leo-kogler** [comment]
Sorry top Tell u, nur its goong the ihrer way

Von meinem iPhone gesendet

**Comment by kirbyfan64** [comment]
And your evidence is...?

**Comment by leo-kogler** [comment]
Prezi came years later than impress.js Impress came in 2009.
Prezi later.

Have a nice day

Leo



Von meinem iPhone gesendet

**Comment by kirbyfan64** [comment]
[Prezi came out in 2009.](https://en.m.wikipedia.org/wiki/Prezi). Impress.js's first Git commit was on [December 28, 2011](https://github.com/impress/impress.js/tree/0c7f9cc2b14f9a5c68f7847f13a7708934fe16e5).

**Comment by leo-kogler** [comment]
I trink you are a dreamer. Beliebe what you do.

Enjoy your weekend

Leo

Von meinem iPhone gesendet

**Comment by phase** [comment]
Instead of demanding that your opinion is completely valid, it would be more productive to _look at the facts_. Prezi came out before Strut (and the library Strut uses, Impress.js). Don't go around making inaccurate claims if you're not going to be open to having your mind changed.

**Comment by Erudition** [comment]
I think he's trolling. Bug closed.
