### ISSUE TITLE
Editor fails to load on website with error

### ISSUE THREAD

**Issue by navinpai** [tantaman/Strut#385]
Web console shows the error as:`SyntaxError: missing ) in parenthetical             require.js:1:712 `. I'm running OSX and tested with both Chrome and Firefox but get the same result.

![Error Console](https://i.imgur.com/TXfTnCz.png)

I'm unsure of this is because of a code change, because I can't find the relevant file in the repo either (or I could try to send a pull request to fix it or atleast take a look at it).

I notice a backlog of issues which might imply strut is no longer being worked upon, but still raising this in hope of seeing this issue fixed!

---
PS. For many years now, Strut has been my go-to tool for snazzy HTML5 presentations. Thanks for making this! 👍

**Comment by tantaman** [comment]
This has been resolved as of today.

http://strut.io/editor
