### ISSUE TITLE
Strut.io: Slide color background lost when Saving then opening

### ISSUE THREAD

**Issue by cems2** [tantaman/Strut#392]
platform:  Strut.io webpage and firefox

Problem:
slide background color not preserved across saves in  .strut format.  instead when opening a file it just changes the color to whatever the background is set for in the current  strut.io session.

steps to reproduce:

1. create a presentation online and add background and surface colors to slides. 
2. save it as a foo.strut file locally
3. **(important step)** change the background of your currently open slides in strut.io
4. open the saved foo.strut

result:
slides seem to be the same except for the background and surface colors.
_Note that if you had not changed the color before reopening it you would not notice this failure_ to preserved the original color

expected result:
all attributes would be preserved including color.

regression:  
saving the file as web-page complete does not lose the colors.  But this then creates a non-editable frozen presentation, so isn't a work around for this problem.

**Comment by tantaman** [comment]
Thanks for the bug report. I'm going to be resuming work on Strut2 which will be the successor to this repo.

It's currently non-functional but you can view the progress here: https://github.com/tantaman/strut2
